pull_request_rules:
  - name: Automated dependabot merge
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=Lint
      - status-success=Docker
    actions:
      merge:
        method: merge