version: '3'

services:
  client:
    networks:
      - frontend
    build:
        context: ./
    command: npm run dev
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"

networks:
  frontend:
